<?php
$z[0]=Array("field","",194,217);
$z[0][4]['name']="id";
$z[1]=Array("field","",251,280);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n					<li class=\"am-g\" > <a href=\"view.php?aid=[field:id/]\" class=\"am-list-item-hd\" >[field:title /]</a>\r\n                      <p style=\"margin:0;float:left;font-size:13px;color:#757575\">发布日期：[field:stime /]</p>\r\n					</li>",366,652);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";
$z[3]=Array("field","",831,854);
$z[3][4]['name']="id";

?>