<?php
$z[0]=Array("field","",85,114);
$z[0][4]['name']="typename";
$z[1]=Array("field","",151,179);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n			linkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\n			picarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\n			textarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\r\n			",854,1110);
$z[2][4]['flag']="f";
$z[2][4]['row']="5";

?>