<field:enterprize itemname="企业名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:enterprize>
<field:membercode itemname="会员编号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:membercode>
<field:membername itemname="会员姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:membername>
<field:gm itemname="商会职务" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gm>
<field:pic itemname="照片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic>
<field:enterprizedesc itemname="企业简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="5000" page="">
</field:enterprizedesc>
