<div class="hot mt1">
   <dl class="tbox light">
    <dt class='light'><strong>{dede:field name="typename"/}</strong><span class="more"><a href="{dede:field name='typeurl'/}">更多...</a></span></dt>
    <dd class='light'>
     <ul class="c1 ico2">
      {dede:arclist sort='hot'  titlelen=42 row=6}
      <li class='dotline'><a href="[field:arcurl/]">[field:title/]</a></li>
      {/dede:arclist}
     </ul>
    </dd>
   </dl>
  </div>