<?php
$z[0]=Array("global","",161,186);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",252,277);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",339,364);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",397,423);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",572,599);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",672,699);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",702,728);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",877,904);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",916,948);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",996,1022);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",1331,1356);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1396,1639);
$z[11][4]['type']="top";
$z[11][4]['row']="10";
$z[11][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[12]=Array("global","",1731,1756);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2569,2699);
$z[13][4]['row']="10";
$z[13][4]['getall']="1";
$z[13][4]['sort']="month";

?>