<?php
$z[0]=Array("global","",161,186);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",252,277);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",339,364);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",397,423);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",551,578);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",651,678);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",681,707);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",862,894);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",942,968);
$z[8][4]['name']="cfg_webname";
$z[9]=Array("global","",1273,1298);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1338,1581);
$z[10][4]['type']="top";
$z[10][4]['row']="10";
$z[10][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[11]=Array("global","",1694,1719);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2527,2657);
$z[12][4]['row']="10";
$z[12][4]['getall']="1";
$z[12][4]['sort']="month";

?>